46Elks provider [WIP]
jandreasn/an-sms pull request #3
Opened 2018-09-28 09:13 UTC by jongotlin

Hi Andreas!

I started to implement 46elks as provider.

In my use case I need number of segments/parts for each sms. That would imply adding `getSegments()` to `MessageInterface`. What do you think?

Both 46Elks and Twilio supports this. I don't know about the other providers.
https://46elks.se/docs/send-sms
https://www.twilio.com/docs/sms/send-messages#send-an-sms-with-twilios-api

2018-10-01 19:32 UTC, andreasnij requested changes
Awesome, thank you! I have suggested a few minor changes.

2018-10-01 19:32 UTC, andreasnij commented on src/Gateway/Provider/FortySixElksGateway.php
> +    protected $password;
Maybe we should name the credential variables `$apiUsername` and `$apiPassword` so that they are not confused with the web login credentials?

2018-10-01 19:32 UTC, andreasnij commented on src/Gateway/Provider/FortySixElksGateway.php
> +            $query
Can we rename `$query` to `$data` since it is a POST request and not a GET?

2018-10-01 19:32 UTC, andreasnij commented on src/Gateway/Provider/FortySixElksGateway.php
> +    protected function buildSendQueryData(MessageInterface $message): array
Can we remove `Query` from this method name?

2018-10-01 19:32 UTC, andreasnij commented on src/Gateway/Provider/FortySixElksGateway.php
> +            'to' => '+' . $message->getTo(),
I don't think the `+` is needed. It's only presentation.

2018-10-02 11:33 UTC, jongotlin commented on src/Gateway/Provider/FortySixElksGateway.php
> +            'to' => '+' . $message->getTo(),
46Elks require the phone numbers to be in E164 format. Hence needed.

2018-10-02 12:09 UTC, andreasnij approved these changes

2018-10-02 12:10 UTC, merged